### ISSUE TITLE
OvenGloves. RemoveFireProtection

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizonsCoreMod#10]
Now it is impossible to wear OvenGloves and still be immune to fire from any other object or potion. When the player starts burning, gloves believe that it is dirty cheater and remove the fire resist without checking its source.
```
    if( tPlayer.isBurning() ) // no fire/lava cheat!
    {
      RemoveFireProtection( pEntity );
      return;
    }
```
Request: make gloves more intelligent and remove only its own fire resist.

**Comment by Dream-Master** [comment]
@Namikon is this a thing you can/will change ?

**Comment by Namikon** [comment]
No. The gloves are *not* meant to protect you from burning. Their intention is to protect you from getting damage from carrying lava buckets in your first days. That's it. Nothing less, nothing more.

**Comment by Ugachaga** [comment]
Not sure that we understand each other. I'm not saying that the gloves should give immunity to burn, but allow other items/potions to give such immunity. In the current version this is not possible when wearing gloves. I would agree that it does not matter if gloves were really relevant only early days, but it is usefull even for drums.

**Comment by Namikon** [comment]
Well, while it is true that the protection effect is removed regardless who applied it, but the case where you fight Blazes in the Nether with your gloves on is rather uncommon. (At least it should be...)
It's a decision to either give basically endless Fire Protection by removing the burn-check, or tell people to remove their gloves when they don't work in their base/transport lava around.

The first version was blocking the damage without potion effects, and that turned out to be very...  "unreliable", so it was changed to utilize the build-in potion effect

**Comment by Ugachaga** [comment]
I agree that this is not a typical situation, but it is possible (and happened to me), and it is possible to avoid by adding checking for potion source.

Fire resistance amplifier means nothing for the gameplay so it could be used as unique identifier for own potion. For for greater accuracy may add duration check as own potion cannot be longer then "MainRegistry.CoreConfig.PotionTimer". If change an amplifier to 1, it may look something like:
```
if( tPlayer.isBurning() 
    && tPlayer.getActivePotionEffect(Potion.fireResistance) != null
    && tPlayer.getActivePotionEffect(Potion.fireResistance).getDuration() <= MainRegistry.CoreConfig.PotionTimer
    && tPlayer.getActivePotionEffect(Potion.fireResistance).getAmplifier() == 1) // no fire/lava cheat!
```
```
          if( isValidLavaContainerItem( tHeldItem ) )
          {
            tPlayer.addPotionEffect( new PotionEffect( Potion.fireResistance.id, MainRegistry.CoreConfig.PotionTimer, 1, false ) ); // amplifier 1
```
This does not solve all the possible incompatibility, but most of them.

**Comment by Namikon** [comment]
Well the amplifier is the Level, and this would give FireResistance II, altho it doesn't exist.
Your suggestion is a duct tape that will cause weird Issues with removing potion effects before they time-out, but I get your point and the chance for this to happen is rather unlikely. Still I need to test this before a change is made

**Comment by Ugachaga** [comment]
Any news here? I could make PR if you have no time or it's low priority.

Actually there is a lot of mods in the pack which is already using "not existing" amplifiers. While the amplifier is positive number it must be pretty safely for use. Just as sample: 
![amp](https://cloud.githubusercontent.com/assets/19178671/23330504/d4cb5b1c-fb81-11e6-831c-ff47f25dd9fc.png)

**Comment by Dream-Master** [comment]
@Namikon

**Comment by Dream-Master** [comment]
@Ugachaga I guess you can add some code here and @Namikon  will look at it when its done.
