### ISSUE TITLE
Bug with Air Filter.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/NewHorizonsCoreMod#110]
The air filter does not stop working, even if the Pollution has become less than the set hysteresis or equal to zero. Continues to work and recycle clean filters.

**Comment by repo-alt** [comment]
Report here: https://github.com/alkcorp/GTplusplus/issues/

**Comment by Pilad** [comment]
> 
> 
> Report here: https://github.com/alkcorp/GTplusplus/issues/

But this machine in NewHorizonsCoreMod : https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilter.java

**Comment by repo-alt** [comment]
Oh, sorry, it's Tec's air filter hatch, I thought you are talking about pollution scrubbers.

**Comment by Dream-Master** [comment]
The air filtr need a rework also because to low filter work for this price of device.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/fef95a6a69d5979296a8569c2e1f7e55c65b414d

**Comment by Pilad** [comment]
Again does not turn off. With a value of 10 000 and does not turn on. Raised to 100 000, then turned on. But again, with a clean chunk, it does not turn off.

**Comment by Dream-Master** [comment]
@Technus any idea what we can do here ?

**Comment by GeicowithaBango** [comment]
oh, that reminds me that I asked for a revaluation of its performance. Did anything changed? The issue for us is that there are no proper ways to deal with the pollution caused by one MBF (we have two now so its getting even worse), therefore we had to disable pollution by a config. Anyways, I would be nice to look into that. I think we shouldn’t rely on gt++ for various reasons.

**Comment by draknyte1** [comment]
Imagine disabling pollution instead of using stuff from GT++. 🤦🏻‍♀️

That’s peak levels of idiocy.

**Comment by GeicowithaBango** [comment]
Idk, I crafted that thing that detects the pollution level. I had a stroke when I saw that it also goes for negative values.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/6b1870ef048da471376fa868bbc62539dca07bb9

**Comment by Technus** [comment]
This also makes it 6x more efficient. As i side effect that i didn't remove.

**Comment by GeicowithaBango** [comment]
could I suggest one thing? I think that higher tier filter would be cool to have, ofc they would have a better performance.

**Comment by Pilad** [comment]
> 
> 
> This also makes it 6x more efficient. As a side effect that I didn't remove.

Completely removed the hysteresis? It does not start automatically when it is very dirty. And it does not stop if there is already no pollution.

**Comment by Pilad** [comment]
From a mallet you can start or stop at any time. As if completely manual mode.

**Comment by Technus** [comment]
It just idles at 32 eut doing nothing when pollution is low

**Comment by Pilad** [comment]
> 
> 
> It just idles at 32 eut doing nothing when pollution is low

Yes.Thank you. Reduces consumption and does not use filters with input bass. Such an algorithm is more correct. Maybe you should add a block pollution detector? So that you can control this air filter? In the detector’s gui, set the threshold number (or by clicking on a block with a screwdriver to increase this value, decrease this value with a shift key) when it will produce a high redstone signal to turn on the air filter.

**Comment by draknyte1** [comment]
Pilad, that literally already exists. 🤦🏻‍♀️

**Comment by Dream-Master** [comment]
@Pilad 
@Technus 
is this fixed?
can this be closed?
