### ISSUE TITLE
Quest suggestion:space leadup.

### ISSUE THREAD

**Issue by Sudoloo** [GTNewHorizons/NewHorizonsCoreMod#9]
After securing my place in hv and the need to reach space arose, i found myself confused and without direction, as i wasnt sure where to get platinum, i didnt know i needed a dire crafting table, and i wouldnt know that i need much more than a rocket to actually survive once i get there, so perhaps a set of space quests could be added to help those new to galacticraft?

**Comment by Dream-Master** [comment]
Sure will add some quest for space age.

**Comment by Sudoloo** [comment]
Ah happy news.thanks dream

**Comment by Dream-Master** [comment]
Can't add that so soon be in Holidays atm.

**Comment by Dream-Master** [comment]
This Quest request is still open but i close it here and open it on The Modpack Project.
