### ISSUE TITLE
Cooling Avaritia infinity ingot

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizonsCoreMod#99]
#### Which modpack version are you using?
2083
![image](https://i.imgur.com/WAyGWES.png)
![image](https://i.imgur.com/zRiNjH4.png)
 ebf recipe using 2kk, but for cooling 20kk

https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/1e30fcc408bc085cb058894195988976f5b1bb5c/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L1484

**Comment by 0lafe** [comment]
To be fair, if you're using this recipe there's kind of a problem

**Comment by Dream-Master** [comment]
@ko5h better report this in the main mod repo

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons
